### 상품권 생성
POST localhost:9000/api/v2/voucher
Content-Type: application/json

{
  "requestType": "PARTNER",
  "requestId": "A00056",
  "amount": "KRW_30000"
}


### 상품권 사용
PUT localhost:9000/api/v2/voucher/use
Content-Type: application/json

{
  "requestType": "PARTNER",
  "requestId": "A00058",
  "code": "30D3D42FB8D04C74A0B5852188EFBA61"
}

### 상품권 폐기
PUT localhost:9000/api/v2/voucher/disable
Content-Type: application/json

{
  "requestType": "PARTNER",
  "requestId": "A00060",
  "code": "30D3D42FB8D04C74A0B5852188EFBA61"
}