server:
  port: 9000
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:13306/project-voucher-mysql
    username: root
    password: root1234
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.orm.jdbc.bind: trace
